name: Continuous Integration
 
on:
  pull_request:
    branches:
      - master
 
jobs:
  automation-test-job:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: npm install and test
        run: |
          npm install
          npm run ci:test